/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vidavid' at '2/16/17 5:11 PM' with Gradle 2.13
 *
 * @author vidavid, @date 2/16/17 5:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
